--- 
title: "Quantitative Genetics Graduate Education Module - Spring 2023"
author: "William A. Cresko"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["book.bib", "packages.bib"]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is the book of materials we will be using for the Quantitative Genetics GEM at the University of Oregon for the Spring Term of 2023"
---
--- 
title: "Quantitative Genetics Graduate Education Module - Spring 2023"
author: "William A. Cresko"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["book.bib", "packages.bib"]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is the book of materials we will be using for the Quantitative Genetics GEM at the University of Oregon for the Spring Term of 2023"
---

# Course Overview

This is the complete set of _course materials_ for the _Quantitative Genetics Graduate Education Module (GEM)_ at the University of Oregon for the Spring of 2023. It is written in **Markdown** so that it can be easily updated. 

In book you will find nearly all the information you will need to complete the course.



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

<!--chapter:end:index.Rmd-->

# Introduction to the course

This is the main set of _course materials_ for the _Quantitative Genetics Graduate Education Module (GEM)_ at the University of Oregon for the Spring of 2023. It is written in **Markdown** so that it can be easily updated. 

In this book you will find nearly all the information you will need to complete the course.


## Instructor
Dr. Bill Cresko, wcresko@uoregon.edu


## Course Information
Class Hours: Monday & Wednesday 10:00-11:20; Friday 10:00-10:50   
Office Hours: F 2 to 3 or by appointment


## Software

- Latest version of R

- Latest version of RStudio

## Course Material

Course Canvas Site   
Course book website - https://wcresko.github.io/UO_Quant_Gen_Text/index.html

## Inclusion and Accessibility

Please tell me your preferred pronouns and/or name, especially if it differs from the class roster. I take seriously my responsibility to create inclusive learning environments. Please notify me if there are aspects of the instruction or design of this course that result in barriers to your participation! You are also encouraged to contact the Accessible Education Center in 164 Oregon Hall at 541-346-1155 or uoaec@uoregon.edu.

I am committed to making this course an inclusive and respectful learning space. Being respectful includes using preferred pronouns for your classmates. Your classmates come from a diverse set of backgrounds and experiences; please avoid assumptions or stereotypes, and aim for inclusivity. Let us know if there are classroom dynamics that impede your (or someone else’s) full engagement.

Because of the COVID-19 pandemic, this course is being delivered entirely remotely. I realize that this situation makes it difficult for some students to interact with the material, for a variety of reasons. I am committed to flexibility during this stressful time and emphasize that I will work with students to overcome difficult barriers as they arise.

<!--chapter:end:01-syllabus.Rmd-->


# Course Schedule

Placeholder


## Background Material
## Heritability 
## Selection Analysis
## Quantitative Genetic Mapping

<!--chapter:end:02-schedule.Rmd-->

# Getting Started with R and Studio

## Introduction to R and RStudio

R is a core computational platform for statistical analysis. It was developed a number of years ago to create an open source environment for advanced computing in statistics and has since become the standard for statistical analysis in the field, replacing commercial packages like SAS and SPSS for the most part. Learning R is an essential part of becoming a scientist who is able to work at the cutting edge of statistical analysis -- or even to perform conventional statistical tests (e.g. a t-test) in a standard way. An important part of R is that it is script-based, which makes it easy to create reproducible analysis pipelines, which is an emerging feature of the open data/open analysis movement in science. This is becoming an important component of publication and sharing of research results, so being able to engage fully with this effort is something that all young scientists should do.

RMarkdown is an extra layer placed on top of R that makes it easy to integrate text explanations of what is going on, native R code/scripts, and R output all in one document. The final result can be put into a variety of forms, including webpages, pdf documents, Word documents, etc. Entire books are now written in RMarkdown and its relatives. It is a great way to make quick webpages, like this document, for instance. It is very easy to use and will be the format that I use to distribute your assignments to you and that you will use to turn in your assignments.

R Projects are a simple way of designating a working directory in which to house files related to a given, well, project. Those files might include primary data and metadata files ready for reading into R, `.R` scripts, Rmarkdown files, and output such as Rmarkdown-rendered .html files or individual plots, for example. The nice thing about organizing your work with R Projects is that you can keep everything needed to reproduce an analysis in a single directory on your computer. You can open an R Project in RStudio by opening the project's index (`.RProj`) file, which will automatically set your working directory to that of the project and facilitate loading any saved environments, etc.

In Chapter 6 we will begin working in R and RStudio, but you can get them installed now (in that order) on your computer, if you haven't already. Get the most recent *released* R version by following this link:

[https://www.r-project.org/](https://www.r-project.org/)

We will do our work using Rstudio, which is a powerful and convenient user interface for R, and can be downloaded from here for installation: [RStudio](https://rstudio.com/products/rstudio/)

### Learning resources

There are tons of resources for learning R and RMarkdown on the internet. Here are just a few, but you will no doubt find your own favorites as you become routine R users.

There is an organized group that is dedicated to training in R called DataCamp (https://www.datacamp.com/). They provide all of the basics for free. They actually have training for most data science platforms. RStudio provides links for training directly related to R and RMarkdown here: [RStudio Training](https://education.rstudio.com/)

There are also many, many R training videos on YouTube. Most of them are very well meaning but may not be as in-depth as you want. 

You can also go the old "paper" manual route by reading the materials provided by R itself: [R manual](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)

In reality, if you want to do almost anything in R, simply type in what you are interested in doing into Google and include "in R" and a whole bunch of links telling you exactly what to do will magically appear. Most of them appear as discussions on websites like `StackOverflow` and `Stats.StackExchange`. In that case, the first thing that you see is the question--usually someone doing it just a bit wrong--so you should scroll down to see the right way to do it in the answers. It is really an amazing resource that will speed you along in nearly every form of analysis that you are interested in.

Please do not hesitate to contact us if you have questions or run into obstacles. The point of this class is to learn by doing, but our aim is that the doing should involve reasonable first efforts supplemented with help if needed. Also, many of your classmates have some experience with R, writing code, or statistics in general, so they are an excellent resource as well!

<!--chapter:end:03-background.Rmd-->


# Organizing and manipulating data files

Placeholder


## Introduction
## Navigating file systems from the command line
### Access to the command line
### Navigating directories and files
#### A quick review of important UNIX commands for navigation and viewing
### Useful UNIX commands for file manipulation
#### A quick review of key UNIX commands for text file searching and manipulation
### A quick word on pipes and carrots
## Data file and data file entry dos and don'ts
## Exercises associated with this chapter:
## Additional learning resources

<!--chapter:end:04-data_organization.Rmd-->


# An Introduction to the R language

Placeholder


## Background
## Why use `R`?
## Important `R` terms and definitions
## Getting started with `R` via the RStudio Environment
### R Programming Basics
#### A note on `R` Markdown
#### Assigning Variables
#### Arithmetic operations with functions
#### Strings
#### Factors
#### Null values
#### Vectors
#### Basic Summary Statistics
#### Getting help to understand functions
## Additional learning resources:

<!--chapter:end:05-R_introduction.Rmd-->


# More R Functions, Complex Objects, Basic Plotting, and RMarkdown

Placeholder


## Background
## More on functions
### More base `R` functions useful for working with vectors
## Indexing vectors
## More complex data objects in `R`
### Lists
### Data frames
#### Creating data frames in `R`
#### Working with pre-loaded base `R` data frames.
#### Reading in data frames in `R`
#### Exporting data frames in `R`
#### Indexing data frames
### Matrices
### A few additional base `R` functions for working with complex `R` objects
## Some brief notes on basic programming in `R`
### conditional statements with `ifelse()`
## The Split-Apply-Combine approach to data analysis
### `replicate()`, `apply()`, `tapply()`, and `aggregate()`
### For loops in `R`
## Fundamentals of plotting in `R`
### Basic plotting with `plot()`
### Histograms using `hist()`
### Boxplots using `boxplot()`
## Additional learning resources:

<!--chapter:end:06-R_morefunc_dfs_plot.Rmd-->


# A brief Introduction to RMarkdown

Placeholder


## What is `RMarkdown`
### `RMarkdown` formatting basics
## Experiment with headers
### Try a third-level header
#### Or a fourth-level header
### `RMarkdown` code chunk options
## Additional learning resources:

<!--chapter:end:07-Rmarkdown.Rmd-->


# Introduction to Probability and Probability Distributions

Placeholder


## Background
## What is probability?
## Random variables & probability
## Probability and the Bernoulli distribution
## Probability rules
## Joint probability
## Conditional probability
## A brief note on likelihood vs. probability
## Probability distributions commonly used in biological statistics 
### Discrete Probability Distributions
#### **Geometric Distribution**
##### The **Geometric Distribution** in practice
#### **Binomial Distribution**
##### The **binomial distribution** in practice
#### **Negative Binomial Distribution**
#### **Poisson Probability Distribution**
##### Poisson Probability Distribution | gene length by bins of 500 nucleotides
##### Poisson Probability Distribution | increasing parameter values of $\lambda$
##### Horse kick deaths in the Prussian army
### **Continuous probability distributions**
#### **Uniform Distribution**
#### **Exponential Distribution**
#### **Gamma Distribution**
#### The Gaussian or Normal Distribution
##### Normal PDF | estimates of mean and variance {.smaller}
##### Why is the Normal distribution special in biology?
##### Parent-offspring resemblance {.smaller}
##### Genetic model of complex traits {.smaller}
##### Distribution of $F_2$ genotypes | really just binomial sampling {.smaller}
##### The Central Limit Theorm
##### A note on z-scores of normal variables
## Exercises associated with this chapter:
## Additional learning resources:

<!--chapter:end:08-probability_probdists.Rmd-->


# Correlation and Simple Linear Regression

Placeholder


## Background
## Covariance and correlation
### Covariance
### Correlation
### Hypothesis tests for correlation
## Simple linear regression
### Hypothesis tests in linear regression
### Linear regression in `R`
### A note on the coefficient of determination
### A note on model II regression
## Additional learning resources:

<!--chapter:end:09-correlation_regression.Rmd-->


# Introduction to Analysis of Variance

Placeholder


## Background
## General linear models
## Single-factor ANOVA
### Single-factor ANOVA hypothesis tests
### ANOVA assumptions
### Post-hoc comparisons
### Single-factor ANOVA in `R`
### A note on nonparametric tests similar to single-factor ANOVA
## Multi-factor ANOVA
### Nested ANOVA
#### Nested ANOVA hypothesis tests
#### Nested ANOVA in `R`
### Factorial ANOVA
#### Factorial ANOVA hypothesis tests
#### Factorial ANOVA in `R`
## Additional learning resources:

<!--chapter:end:10-ANOVA_intro.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:21-references.Rmd-->

